$(document).ready(function(){
	// Make the clock's section with figure (the clockface) and article (the text)
	newClock ='<figure>';
	newClock+='<img id="pie_text"   src="pie/pie.svg" />';
	newClock+='<div id="pie_face">';
	newClock+='<img id="pie_hours"   src="pie/pie60.svg" />';
	newClock+='<img id="pie_minutes" src="pie/pie60.svg" />';
	newClock+='<img id="pie_seconds" src="pie/pie60.svg" />';
	newClock+='<img id="pie_years"   src="pie/pie36.svg" />';
	newClock+='<img id="pie_months"  src="pie/pie36.svg" />';
	newClock+='<img id="pie_dates"   src="pie/pie36.svg" />';
	newClock+='<img id="pie_weeks"   src="pie/pie36.svg" />';
	newClock+='<img id="pie_days"    src="pie/pie36.svg" />';
	newClock+='</div>';
	newClock+="</figure>";
	newClock+="<article>";
	newClock+="<h2>Pie by Cis</h2>";
	newClock+="<p>This clockwork provides hours, mintutes and seconds as 60 &deg; pies and years, months, dates, weeks and days as 36 &deg; pies.</p>";
	newClock+="</article>";
	var nodeRef=document.createElement("section");
	nodeRef.setAttribute("id","pie");
	nodeRef.style.display="none";
	nodeRef.innerHTML=newClock;
	document.getElementsByTagName("body")[0].appendChild(nodeRef);

	document.getElementById("pie_text").style.width ="100%";
	document.getElementById("pie_text").style.height="100%";
	document.getElementById("pie_text").style.top   ="0px";
	document.getElementById("pie_text").style.left  ="0px";

	elem=document.getElementById("pie_face").getElementsByTagName("*");
	for (var i = 0; i < elem.length; i++) {
		elem[i].style.position="absolute";
		elem[i].style.top     ="0px";
		elem[i].style.left    ="0px";
		elem[i].style.width   ="100%";
		elem[i].style.height  ="100%";
	};

	document.getElementById("pie_hours").style.transform="rotate(30deg)";
	document.getElementById("pie_hours").style.oTransform="rotate(30deg)";
	document.getElementById("pie_hours").style.msTransform="rotate(30deg)";
	document.getElementById("pie_hours").style.mozTransform="rotate(30deg)";
	document.getElementById("pie_hours").style.webkitTransform="rotate(30deg)";
	document.getElementById("pie_minutes").style.transform="rotate(90deg)";
	document.getElementById("pie_minutes").style.oTransform="rotate(90deg)";
	document.getElementById("pie_minutes").style.msTransform="rotate(90deg)";
	document.getElementById("pie_minutes").style.mozTransform="rotate(90deg)";
	document.getElementById("pie_minutes").style.webkitTransform="rotate(90deg)";
	document.getElementById("pie_seconds").style.transform="rotate(150deg)";
	document.getElementById("pie_seconds").style.oTransform="rotate(150deg)";
	document.getElementById("pie_seconds").style.msTransform="rotate(150deg)";
	document.getElementById("pie_seconds").style.mozTransform="rotate(150deg)";
	document.getElementById("pie_seconds").style.webkitTransform="rotate(150deg)";

	document.getElementById("pie_years").style.transform="rotate(342deg)";
	document.getElementById("pie_years").style.oTransform="rotate(342deg)";
	document.getElementById("pie_years").style.msTransform="rotate(342deg)";
	document.getElementById("pie_years").style.mozTransform="rotate(342deg)";
	document.getElementById("pie_years").style.webkitTransform="rotate(342deg)";
	document.getElementById("pie_months").style.transform="rotate(306deg)";
	document.getElementById("pie_months").style.oTransform="rotate(306deg)";
	document.getElementById("pie_months").style.msTransform="rotate(306deg)";
	document.getElementById("pie_months").style.mozTransform="rotate(306deg)";
	document.getElementById("pie_months").style.webkitTransform="rotate(306deg)";
	document.getElementById("pie_dates").style.transform="rotate(270deg)";
	document.getElementById("pie_dates").style.oTransform="rotate(270deg)";
	document.getElementById("pie_dates").style.msTransform="rotate(270deg)";
	document.getElementById("pie_dates").style.mozTransform="rotate(270deg)";
	document.getElementById("pie_dates").style.webkitTransform="rotate(270deg)";
	document.getElementById("pie_weeks").style.transform="rotate(234deg)";
	document.getElementById("pie_weeks").style.oTransform="rotate(234deg)";
	document.getElementById("pie_weeks").style.msTransform="rotate(234deg)";
	document.getElementById("pie_weeks").style.mozTransform="rotate(234deg)";
	document.getElementById("pie_weeks").style.webkitTransform="rotate(234deg)";
	document.getElementById("pie_days").style.transform="rotate(198deg)";
	document.getElementById("pie_days").style.oTransform="rotate(198deg)";
	document.getElementById("pie_days").style.msTransform="rotate(198deg)";
	document.getElementById("pie_days").style.mozTransform="rotate(198deg)";
	document.getElementById("pie_days").style.webkitTransform="rotate(198deg)";

	var webClock=setInterval(function(){pie()},1);
	function pie(){
		w= document.getElementById("pie").firstChild.offsetWidth;
		h= document.getElementById("pie").firstChild.offsetHeight;
		wh=Math.min(w,h)*0.83;
		document.getElementById("pie_face").style.position="absolute";
		document.getElementById("pie_face").style.width   =wh+"px";
		document.getElementById("pie_face").style.height  =wh+"px";
		document.getElementById("pie_face").style.left    =((w-wh)/2).toString()+"px";
		document.getElementById("pie_face").style.top     =((h-wh)/2).toString()+"px";

	    var rHours  =(hourVar%12*3600000+minuteVar*60000+secondVar*1000+miliVar)/43200000*100;
	    var rMinutes=(minuteVar*60000+secondVar*1000+miliVar)/3600000*100;
	    var rSeconds=(secondVar*1000+miliVar)/60000*100;
	    var rYears  =yearVar%100;
	    var rMonths =(monthVar+1)/12*100;
	    var rDates  =dateVar/31*100;
	    var rWeeks  =weekVar/52*100;
	    var rDays   =(dayVar)/7*100;
		document.getElementById("pie_hours").style.width =rHours.toString()+"%";
		document.getElementById("pie_hours").style.height=rHours.toString()+"%";
		document.getElementById("pie_hours").style.top   =((100-rHours)/2).toString()+"%";
		document.getElementById("pie_hours").style.left  =((100-rHours)/2).toString()+"%";
		document.getElementById("pie_minutes").style.width =rMinutes.toString()+"%";
		document.getElementById("pie_minutes").style.height=rMinutes.toString()+"%";
		document.getElementById("pie_minutes").style.top   =((100-rMinutes)/2).toString()+"%";
		document.getElementById("pie_minutes").style.left  =((100-rMinutes)/2).toString()+"%";
		document.getElementById("pie_seconds").style.width =rSeconds.toString()+"%";
		document.getElementById("pie_seconds").style.height=rSeconds.toString()+"%";
		document.getElementById("pie_seconds").style.top   =((100-rSeconds)/2).toString()+"%";
		document.getElementById("pie_seconds").style.left  =((100-rSeconds)/2).toString()+"%";

		document.getElementById("pie_years").style.width =rYears.toString()+"%";
		document.getElementById("pie_years").style.height=rYears.toString()+"%";
		document.getElementById("pie_years").style.top   =((100-rYears)/2).toString()+"%";
		document.getElementById("pie_years").style.left  =((100-rYears)/2).toString()+"%";
		document.getElementById("pie_months").style.width =rMonths.toString()+"%";
		document.getElementById("pie_months").style.height=rMonths.toString()+"%";
		document.getElementById("pie_months").style.top   =((100-rMonths)/2).toString()+"%";
		document.getElementById("pie_months").style.left  =((100-rMonths)/2).toString()+"%";
		document.getElementById("pie_dates").style.width =rDates.toString()+"%";
		document.getElementById("pie_dates").style.height=rDates.toString()+"%";
		document.getElementById("pie_dates").style.top   =((100-rDates)/2).toString()+"%";
		document.getElementById("pie_dates").style.left  =((100-rDates)/2).toString()+"%";
		document.getElementById("pie_weeks").style.width =rWeeks.toString()+"%";
		document.getElementById("pie_weeks").style.height=rWeeks.toString()+"%";
		document.getElementById("pie_weeks").style.top   =((100-rWeeks)/2).toString()+"%";
		document.getElementById("pie_weeks").style.left  =((100-rWeeks)/2).toString()+"%";
		document.getElementById("pie_days").style.width =rDays.toString()+"%";
		document.getElementById("pie_days").style.height=rDays.toString()+"%";
		document.getElementById("pie_days").style.top   =((100-rDays)/2).toString()+"%";
		document.getElementById("pie_days").style.left  =((100-rDays)/2).toString()+"%";
	};
});